version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27000:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo

  app:
    restart: always
    build: ./data-api
    working_dir: /data-api
    volumes:
      - ./data-api:/data-api
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - mongo
    